### ISSUE TITLE
Wrong khronos_intptr_t and khronos_ssize_t

### ISSUE THREAD

**Issue by tpetazzoni** [mdrjr/c2_mali#1]
The reference Khronos registry, and mesa3d both defines ```khronos_intptr_t``` and ```khronos_ssize_t``` as follows:

```
#ifdef _WIN64
typedef signed   long long int khronos_intptr_t;
typedef unsigned long long int khronos_uintptr_t;
typedef signed   long long int khronos_ssize_t;
typedef unsigned long long int khronos_usize_t;
#else
typedef signed   long  int     khronos_intptr_t;
typedef unsigned long  int     khronos_uintptr_t;
typedef signed   long  int     khronos_ssize_t;
typedef unsigned long  int     khronos_usize_t;
#endif
```

However, the copy of ```khrplatform.h``` in odroid-mali defines them as:

```
typedef int           khronos_intptr_t;
typedef int           khronos_ssize_t;
```

This causes a build failure with for example the ```libepoxy``` package, which has its own definition of ```khronos_intptr_t``` and ```khronos_ssize_t``` that matches the Khronos registry definition, but conflicts with the one provided by odroid-mali.

I think odroid-mali should use the Khronos registry definition for those types, but since I'm unable to runtime test if this change still keeps odroid-mali working (no Odroid hardware), I prefer to report a bug.

**Comment by mdrjr** [comment]
4f8a541693fee5fdcaa162a7fd8922861a4ba0a9 fixes it.
